spring.application.name=DesignPattern
# ===============================
# CONFIGURACAO DO SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURACAO DO H2 DATABASE
# ===============================
# Define a URL do banco em memoria (chamamos de "checkoutdb")
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root



spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# CONFIGURACAO DO SPRING DATA JPA / HIBERNATE
# ===============================
# Dialeto especifico para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ddl-auto=update faz com que o Spring crie as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Hibernate esta executando.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# 1. Puxando a chave do JWT
api.security.token.secret=PALMEIRAS_MAIOR_TIME_DO_BRASIL
api.security.token.issuer=DESIGNPATTERN_PALMEIRAS_TOP_1

spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.model=gemini-3.6-flash